development:
  adapter: postgresql
  encoding: unicode
  database: google_books_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: google_books_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: google_books_production
  pool: 5
  username: postgres
  password: postgres
