defaults: &defaults
  api_key: AIzaSyBz_mQZSHuKOrni54iGJvyJIT6Jb3oS1cA
  application_name: Google Books
  application_version: 1.0.0
  country: US
  default_query: ruby on rails
  per_page: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
